FROM maven:3.8.7-openjdk-18-slim
COPY ../src /usr/src/mymaven/src
COPY ../pom.xml /usr/src/mymaven/pom.xml
WORKDIR /usr/src/mymaven
RUN ["mvn","clean","install","-DskipTests"]

FROM docker.io/openjdk:18-slim
RUN mkdir /server
COPY --from=0 "/usr/src/mymaven/target/*.jar" /server/release.jar
WORKDIR /server
CMD ["java","-jar","release.jar"]
